# SonarQube Project Configuration
sonar.projectKey=mizan-app
sonar.projectName=Mizan App
sonar.projectVersion=1.0.0

# Path to the source directories
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, **/*.test.js

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# SonarQube Server Host URL (Default local host)
# Ganti URL ini jika Anda menggunakan server SonarQube remote atau SonarCloud
sonar.host.url=http://localhost:9000
